#!/usr/bin/python

import MySQLdb
import csv

print "creating database"

db = MySQLdb.connect("localhost", "root", "D@t@b@ses333", "CarDatabase")
	
cursor = db.cursor()

sql = """
	CREATE TABLE MANUFACTURER
		(
			ManuID VARCHAR(60) NOT NULL PRIMARY KEY,
			TotalSales INT NULL,
			LeastRecentSales INT NULL,
			RecentMonthSales INT NULL,
			Growth DECIMAL(5,2) NULL
		);
	CREATE TABLE RECALLS
		(
			Year INT NULL,
			ManuID VARCHAR(60) NULL, 
			Model VARCHAR(60) NULL,
			NumberAffected INT NULL,
			Issue VARCHAR(60) NULL
		);
	CREATE TABLE TOWS
		(
			TowID INT NOT NULL PRIMARY KEY,
			Firm VARCHAR(60) NULL,
			Address VARCHAR(200) NULL,
			Phone VARCHAR(60) NULL,
			Manufacturer VARCHAR(60) NULL,
			Model VARCHAR(60) NULL		
		);
	CREATE TABLE CAR
		(
			CarID VARCHAR(60) NOT NULL PRIMARY KEY,
			Model VARCHAR(60) NOT NULL,
			Year INT NULL,
			VehicleType VARCHAR(60) NULL,
			ManuID VARCHAR(60) NULL 
		);
	CREATE TABLE ENGINE
		(
			EngineID VARCHAR(60) PRIMARY KEY,
			CarID VARCHAR(60) NULL,
			Cylinders INT NULL,
			Displacement DECIMAL(3,1) NULL,
			Horsepower INT NULL,
			FOREIGN KEY (CarID) REFERENCES CAR(CarID) ON DELETE CASCADE
		);
	CREATE TABLE TRANSMISSION
		(
			CarID VARCHAR(60) NULL,
			Type VARCHAR(60) NULL,
			Gears INT NULL,
			Drivetrain VARCHAR(60) NULL,
			FOREIGN KEY (CarID) REFERENCES CAR(CarID) ON DELETE CASCADE
		);
	CREATE TABLE GAS_INFO
		(
			CarID VARCHAR(60) NOT NULL,
			CO DECIMAL(10,5) NOT NULL,
			COO DECIMAL(10,5) NOT NULL,
			NOX DECIMAL(10,5) NOT NULL,
			MPG DECIMAL(10,5) NOT NULL,
			TotalEmissions DECIMAL(10,5) NULL,
			FOREIGN KEY (CarID) REFERENCES CAR(CarID) ON DELETE CASCADE
		);

	CREATE TRIGGER insert_growth BEFORE INSERT ON MANUFACTURER
	FOR EACH ROW SET NEW.Growth = (NEW.RecentMonthSales - NEW.LeastRecentSales)/(NEW.LeastRecentSales);
	
	CREATE TRIGGER total_emmissions BEFORE INSERT ON GAS_INFO
	FOR EACH ROW SET NEW.TotalEmissions = NEW.CO + NEW.COO + NEW.NOX;	

	CREATE TRIGGER check_mpg_too_high BEFORE INSERT ON GAS_INFO
	FOR EACH ROW SET NEW.MPG = IF(NEW.MPG > 1000, NULL, NEW.MPG);	

	CREATE TRIGGER check_mpg_zero BEFORE INSERT ON GAS_INFO
	FOR EACH ROW SET NEW.MPG = IF(NEW.MPG < 1, NULL, NEW.MPG);
	
	CREATE PROCEDURE remove_data ()
	BEGIN
		DELETE FROM GAS_INFO;
		DELETE FROM TOWS;
		DELETE FROM RECALLS;
		DELETE FROM TRANSMISSION;
		DELETE FROM CAR;
		DELETE FROM MANUFACTURER;
		DELETE FROM ENGINE;	
	END;"""
create = ' '.join(sql.split())

cursor.execute(create)

print "create database complete"


