#!/usr/bin/python

import MySQLdb
import csv

db = MySQLdb.connect("localhost", "root", "D@t@b@ses333", "CarDatabase")
	
cursor = db.cursor()

sql1 = """DROP TABLE CAR;"""
sql2 = """DROP TABLE ENGINE;"""
sql3 = """DROP TABLE TRANSMISSION;"""
sql4 = """DROP TABLE GAS_INFO;"""
sql5 = """DROP TABLE MANUFACTURER;"""
sql6 = """DROP TABLE RECALLS;"""
sql7 = """DROP TABLE TOWS;"""
sql8 = """DROP PROCEDURE remove_data;"""

try:
	cursor.execute(sql1)
	print "Dropping CAR"
except:
	print "Already dropped CAR"
try:
	cursor.execute(sql2)
	print "Dropping ENGINE"
except:
	print "Already dropped ENGINE"
try:
	cursor.execute(sql3)
	print "Dropping TRANSMISSION"
except:
	print "Already dropped TRANSMISSION"
try:
	cursor.execute(sql4)
	print "Dropping GAS_INFO"
except:
	print "Already dropped GAS_INFO"
try:
	cursor.execute(sql5)
	print "Dropping MANUFACTURER"
except:
	print "Already dropped MANUFACTURER"
try:
	cursor.execute(sql6)
	print "Dropping RECALLS"
except:
	print "Already dropped RECALLS"
try:
	cursor.execute(sql7)
	print "Dropping TOWS"
except:
	print "Already dropped TOWS"
try:
	cursor.execute(sql8)
	print "Dropping Procedure"
except:
	print "Already dropped Procedure"

